### ISSUE TITLE
Add support for blazor NavLink

### ISSUE THREAD

**Issue by hades200082** [desmondinho/tailwind-merge-dotnet#5] opened 2024-07-31 11:37 UTC
```razor
<NavLink href="/admin/dashboard" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white" Match="NavLinkMatch.All" ActiveClass="text-white bg-gray-900">Dashboard</NavLink>
```

Default classes: `rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white`

If the NavLink matches the current route, based on the `Match` property, Blazor adds the `ActiveClass` classes to the existing classes.

`ActiveClass="text-white bg-gray-900"`

This results in: `rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white text-white bg-gray-900` which duplicates the text colour and background colour classes - which ones will take priority?

In JavaScript based frameworks tw-merge handles this by ensuring that the order the classes are specified dictates the priority, with classes specified later overriding those from earlier in the list.

How can we do this for .NET?

**Comment by desmondinho** [comment] 2024-07-31 14:32
> In JavaScript based frameworks tw-merge handles this by ensuring that the order the classes are specified dictates the priority, with classes specified later overriding those from earlier in the list.

This utility does exactly the same but the problem we are facing here is actually caused by the internal implementation of the [Blazor NavLink component](https://github.com/dotnet/aspnetcore/blob/3f1acb59718cadf111a0a796681e3d3509bb3381/src/Components/Web/src/Routing/NavLink.cs#L93). 

As the consumers of this component, we don't have any control over the internal logic that applies active state classes when the component re-renders. That would be the case even for a JS-based frameworks.

I have some ideas of what we could try in this case. I will try them out later today and get back to you :)

**Comment by desmondinho** [comment] 2024-07-31 15:18
@hades200082

So, here is the solution I've come up with.

1. Create a custom navlink component inheriting from the native `NavLink` component.
2. Add the additional `Class` parameter that will be used instead of the `class` attribute.

_If you don't want to add any parameters to the component, you could just pass the `class` attribute as you do, but you have to manually extract it using the `AdditionalAttributes` parameter that is inherited from `NavLink`. [See this for the reference.](https://github.com/dotnet/aspnetcore/blob/3f1acb59718cadf111a0a796681e3d3509bb3381/src/Components/Web/src/Routing/NavLink.cs#L76)_

3. Override the base `BuildRenderTree` lifecycle method, so you will merge CSS classes just before rendering the component.

> [!NOTE]  
> I've used [the new technique](https://medium.com/@malarsharmila/introduction-to-the-unsafeaccessorattribute-class-in-net-8-0-d3a55ec15762) to access the `_isActive` private field of the `NavLink` to track the state instead of the traditional reflection.

Here is the full code:

```csharp
public partial class CustomLink : NavLink
{
    /// <summary>
    /// Gets or sets CSS class names that will be applied to the component.
    /// </summary>
    [Parameter] public string? Class { get; set; }

    [Inject] private TwMerge TwMerge { get; set; } = default!;

    /// <inheritdoc/>
    protected override void BuildRenderTree( RenderTreeBuilder builder )
    {
        CssClass = TwMerge.Merge( Class, GetActiveClasses() );
        base.BuildRenderTree( builder );
    }

    [UnsafeAccessor( UnsafeAccessorKind.Field, Name = "_isActive" )]
    private static extern ref bool GetActiveState( NavLink navLink );

    private string? GetActiveClasses() => GetActiveState( this ) ? ActiveClass : default;
}
```

And the usage:

```razor
<CustomLink Match="@NavLinkMatch.All"
            Class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-gray-700 hover:text-white"
            ActiveClass="text-white bg-gray-900"
            href="/admin/dashboard">
    Dashboard
</CustomLink>
```

Please give it a try and tell me what you think about it!

**Comment by desmondinho** [comment] 2024-08-01 14:54
Closing this as not related to the library's functionality.

**Closed by desmondinho** 2024-08-01 14:54 UTC

**Comment by hades200082** [comment] 2024-08-09 16:01
I'm trying your solution @desmondinho but it's telling me the BuildRenderTree - Member with the same signature already exists.

![image](https://github.com/user-attachments/assets/cb888f28-99ab-4c1e-a242-11d889f2c35e)

**Comment by desmondinho** [comment] 2024-08-09 16:10
> Member with the same signature already exists

Hey @hades200082,

That's because this method is auto-generated under the hood when you create a `.razor` file. And now you've actually just kind of made a duplicate of this method. So, you have two options here:

1. Remove the `.razor` file and move everything into the code-behind aka `.razor.cs` file.
2. Move the code from the `BuildRenderTree` method to the .razor as follows:

```razor
@* ... *@

@{
    CssClass = TwMerge.Merge( Class, GetActiveClasses() );
    base.BuildRenderTree( builder );
}

@code { @* ... *@ }
```

**Comment by hades200082** [comment] 2024-08-09 17:00
That makes sense. Thanks.

**Comment by desmondinho** [comment] 2024-08-09 17:10
> That makes sense. Thanks.

Feel free to ask if you face any new obstacles. I hope you will enjoy using this library!

Happy coding :)
